version: '3.8'

services:
  rating-bot:
    build: .
    container_name: rating-telegram-bot
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Опционально: база данных PostgreSQL для продакшена
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: rating-bot-db
  #   environment:
  #     POSTGRES_DB: rating_bot
  #     POSTGRES_USER: bot_user
  #     POSTGRES_PASSWORD: bot_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
